library(AnnotationHub)
library("biomaRt")
library(data.table)
library(DescTools)
library("DESeq2")
library (EDASeq)
library (edgeR)
library(ggfortify) 
library(ggplot2)
library(ggplot2)  
library(ggVennDiagram)
library(gridExtra)
library("GWENA")
library(igraph)
library("readr")
library(readr)
library(readr)                                                                                                            #
library("readxl")
library(viridis)
library("xlsx")
library("xlsx")
library("gtools")
